# Name of website
title: NOVAthesis LaTeX template

# Description of website
description: A LaTeX template for thesis, dissertations and similar monography-like documents

# Your name to show in the footer
author: João Lourenço

# logo
logo: NOVAthesisFiles/Images/novathesis_cover_image.jpg

show_downloads: true
theme: jekyll-theme-minimal